FROM python:3.10-slim

WORKDIR /app

ENV TZ=Asia/Shanghai
RUN apt-get update && apt-get install -y tzdata
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone


COPY api/requirements.txt 1.txt
COPY kuonasr/requirements/base.txt 2.txt
COPY kuonasr/requirements/api_aliyun.txt 3.txt
RUN pip install --no-cache-dir -r 1.txt && \
    pip install --no-cache-dir -r 2.txt && \
    pip install --no-cache-dir -r 3.txt


ENV ALIYUN_API_KEY=""

RUN mkdir -p /app/api/logs && \
    chmod 777 /app/api/logs

EXPOSE 23333

CMD ["python", "api/app/run.py"] 