FROM python:3.10-slim

WORKDIR /app

# 安装依赖
COPY api/requirements.txt 1.txt
COPY kuonasr/requirements/base.txt 2.txt
COPY kuonasr/requirements/api_aliyun.txt 3.txt
RUN pip install --no-cache-dir -r 1.txt && \
    pip install --no-cache-dir -r 2.txt && \
    pip install --no-cache-dir -r 3.txt

# 设置环境变量
ENV ALIYUN_API_KEY=""

EXPOSE 23333

CMD ["python", "api/app/run.py"] 